// packages/vue/lib/responsiveLayout.vue
<script setup lang="ts" name="responsiveLayout">
import { useResponsiveLayoutStore } from "./store";
import { ref, onMounted, onUnmounted, watch, useSlots } from "vue";

interface ClassNames {
  nav?: string;
  aside?: string;
  main?: string;
}

interface Props {
  className?: string;
  classNames?: ClassNames;
  navWidth?: string;
  asideWidth?: string;
}

const props = withDefaults(defineProps<Props>(), {
  navWidth: "24rem",
  asideWidth: "24rem",
});

const slots = useSlots();
const store = useResponsiveLayoutStore();
const navRef = ref<HTMLElement | null>(null);
const asideRef = ref<HTMLElement | null>(null);
const mainRef = ref<HTMLElement | null>(null);

const hasNav = Boolean(slots.nav);
const hasAside = Boolean(slots.aside);

const scrollTo = (
  target: "nav" | "aside" | "main",
  behavior: ScrollBehavior = "smooth"
) => {
  switch (target) {
    case "nav":
      if (hasNav) navRef.value?.scrollIntoView({ behavior });
      else mainRef.value?.scrollIntoView({ behavior });
      break;
    case "aside":
      if (hasAside) asideRef.value?.scrollIntoView({ behavior });
      else mainRef.value?.scrollIntoView({ behavior });
      break;
    case "main":
      mainRef.value?.scrollIntoView({ behavior });
      break;
  }
};

const handleResize = () => {
  const isMobile = window.matchMedia("(max-width: 768px)").matches;

  if (isMobile) {
    store.setOpenNav(false);
    store.setOpenAside(false);
    scrollTo("main", "auto");
  } else {
    store.setOpenNav(hasNav);
    store.setOpenAside(false);
  }
};

onMounted(() => {
  handleResize();
  window.addEventListener("resize", handleResize);

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        const targetId = entry.target.id;
        if (entry.isIntersecting) {
          switch (targetId) {
            case "AppNav":
              store.setOpenNav(true);
              store.setOpenAside(false);
              break;
            case "AppAside":
              store.setOpenAside(true);
              store.setOpenNav(false);
              break;
            case "AppMain":
              store.setOpenNav(false);
              store.setOpenAside(false);
              break;
          }
        }
      });
    },
    { threshold: [1] }
  );

  [mainRef.value, asideRef.value, navRef.value].forEach((el) => {
    if (el instanceof HTMLElement) observer.observe(el);
  });

  onUnmounted(() => {
    window.removeEventListener("resize", handleResize);
    observer.disconnect();
  });
});

watch([() => store.openNav, () => store.openAside], () => {
  const isMobile = window.matchMedia("(max-width: 768px)").matches;
  if (!isMobile) return;

  if (!store.openAside && !store.openNav) {
    scrollTo("main");
  } else if (store.openAside) {
    scrollTo("aside");
  } else if (store.openNav) {
    scrollTo("nav");
  }
});

const cn = (...classNames: (string | undefined | null | false)[]) => {
  return classNames.filter(Boolean).join(" ");
};

const layoutStyles = {
  "--nav-width": props.navWidth,
  "--aside-width": props.asideWidth,
  scrollbarWidth: "none" as const,
};
</script>

<template>
  <section
    :class="
      cn(
        'h-[100dvh] w-[100dvw]',
        'flex md:overflow-hidden',
        'overflow-x-scroll overflow-y-hidden md:overflow-visible snap-x snap-mandatory md:snap-none',
        className
      )
    "
    :style="layoutStyles">
    <nav
      v-if="hasNav"
      ref="navRef"
      id="AppNav"
      :class="
        cn(
          'h-full relative',
          'w-screen flex-shrink-0',
          'snap-center md:snap-none',
          'md:transition-all md:duration-300 md:overflow-hidden',
          'md:w-[var(--nav-width)]',
          !store.openNav && 'md:!w-0',
          classNames?.nav
        )
      ">
      <slot name="nav" />
    </nav>
    <main
      ref="mainRef"
      id="AppMain"
      :class="
        cn(
          'h-full',
          'w-screen flex-shrink-0',
          'snap-center md:snap-none',
          'md:transition-all md:duration-300',
          'md:w-full',
          store.openNav &&
            hasNav &&
            !store.openAside &&
            'md:!w-[calc(100%-var(--nav-width))]',
          !store.openNav &&
            store.openAside &&
            hasAside &&
            'md:!w-[calc(100%-var(--aside-width))]',
          store.openNav &&
            hasNav &&
            store.openAside &&
            hasAside &&
            'md:!w-[calc(100%-var(--nav-width)-var(--aside-width))]',
          classNames?.main
        )
      ">
      <slot name="main" />
    </main>
    <aside
      v-if="hasAside"
      ref="asideRef"
      id="AppAside"
      :class="
        cn(
          'h-full relative',
          'w-screen flex-shrink-0',
          'snap-center md:snap-none',
          'md:transition-all md:duration-300 md:overflow-hidden',
          'md:w-[var(--aside-width)]',
          !store.openAside && 'md:!w-0',
          classNames?.aside
        )
      ">
      <slot name="aside" />
    </aside>
  </section>
</template>

// packages/react/lib/responsiveLayout.tsx
import { useCallback, useEffect, useRef } from "react";
import { useResponsiveLayoutStore } from "./store";
export function cn(...classNames: (string | undefined | null | false)[]) {
  return classNames.filter(Boolean).join(" ");
}
export interface ClassNames {
  nav?: string;
  aside?: string;
  main?: string;
}
export interface ResponsiveLayoutProps {
  appNav?: React.ReactNode;
  appAside?: React.ReactNode;
  appMain: React.ReactNode;
  className?: string;
  classNames?: ClassNames;
  navWidth?: string;
  asideWidth?: string;
}
export const ResponsiveLayout = ({
  appNav,
  appAside,
  appMain,
  className,
  classNames,
  navWidth = "24rem",
  asideWidth = "24rem",
}: ResponsiveLayoutProps) => {
  const navRef = useRef<HTMLDivElement>(null);
  const asideRef = useRef<HTMLDivElement>(null);
  const mainRef = useRef<HTMLDivElement>(null);

  const hasNav = Boolean(appNav);
  const hasAside = Boolean(appAside);

  const openNav = useResponsiveLayoutStore((state) => state.openNav);
  const openAside = useResponsiveLayoutStore((state) => state.openAside);
  const setOpenNav = useResponsiveLayoutStore((state) => state.setOpenNav);
  const setOpenAside = useResponsiveLayoutStore((state) => state.setOpenAside);

  const scrollTo = useCallback(
    (target: "nav" | "aside" | "main", behavior: ScrollBehavior = "smooth") => {
      switch (target) {
        case "nav":
          if (hasNav) navRef.current?.scrollIntoView({ behavior });
          else mainRef.current?.scrollIntoView({ behavior });
          break;
        case "aside":
          if (hasAside) asideRef.current?.scrollIntoView({ behavior });
          else mainRef.current?.scrollIntoView({ behavior });
          break;
        case "main":
          mainRef.current?.scrollIntoView({ behavior });
          break;
      }
    },
    [hasNav, hasAside]
  );

  useEffect(() => {
    const handleResize = () => {
      const isMobile = window.matchMedia("(max-width: 768px)").matches;

      if (isMobile) {
        setOpenNav(false);
        setOpenAside(false);
        scrollTo("main", "auto");
      } else {
        setOpenNav(hasNav);
        setOpenAside(false);
      }
    };

    handleResize();

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, [hasNav, hasAside, scrollTo, setOpenNav, setOpenAside]);

  useEffect(() => {
    const isMobile = window.matchMedia("(max-width: 768px)").matches;
    if (!isMobile) return;

    if (!openAside && !openNav) {
      scrollTo("main");
    } else if (openAside) {
      scrollTo("aside");
    } else if (openNav) {
      scrollTo("nav");
    }
  }, [openNav, openAside]);

  useEffect(() => {
    const isMobile = window.matchMedia("(max-width: 768px)").matches;
    if (!isMobile) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const targetId = entry.target.id;
          if (entry.isIntersecting) {
            switch (targetId) {
              case "AppNav":
                setOpenNav(true);
                setOpenAside(false);
                break;
              case "AppAside":
                setOpenAside(true);
                setOpenNav(false);
                break;
              case "AppMain":
                setOpenNav(false);
                setOpenAside(false);
                break;
            }
          }
        });
      },
      { threshold: [1] }
    );

    [mainRef.current, asideRef.current, navRef.current].forEach((el) => {
      if (el instanceof HTMLDivElement) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  const layoutStyles = {
    "--nav-width": navWidth,
    "--aside-width": asideWidth,
    scrollbarWidth: "none",
  } as React.CSSProperties;

  return (
    <section
      className={cn(
        "h-[100dvh] w-[100dvw]",
        "flex md:overflow-hidden",
        "overflow-x-scroll overflow-y-hidden md:overflow-visible snap-x snap-mandatory md:snap-none",
        className
      )}
      style={layoutStyles}>
      {hasNav && (
        <nav
          ref={navRef}
          id="AppNav"
          className={cn(
            "h-full relative",
            "w-screen flex-shrink-0",
            "snap-center md:snap-none",
            "md:transition-all md:duration-300 md:overflow-hidden",
            "md:w-[var(--nav-width)]",
            !openNav && "md:!w-0",
            classNames?.nav
          )}>
          {appNav}
        </nav>
      )}
      <main
        ref={mainRef}
        id="AppMain"
        className={cn(
          "h-full",
          "w-screen flex-shrink-0",
          "snap-center md:snap-none",
          "md:transition-all md:duration-300",
          "md:w-full",
          openNav &&
            hasNav &&
            !openAside &&
            "md:!w-[calc(100%-var(--nav-width))]",
          !openNav &&
            openAside &&
            hasAside &&
            "md:!w-[calc(100%-var(--aside-width))]",
          openNav &&
            hasNav &&
            openAside &&
            hasAside &&
            "md:!w-[calc(100%-var(--nav-width)-var(--aside-width))]",
          classNames?.main
        )}>
        {appMain}
      </main>
      {hasAside && (
        <aside
          ref={asideRef}
          id="AppAside"
          className={cn(
            "h-full relative",
            "w-screen flex-shrink-0",
            "snap-center md:snap-none",
            "md:transition-all md:duration-300 md:overflow-hidden",
            "md:w-[var(--aside-width)]",
            !openAside && "md:!w-0",
            classNames?.aside
          )}>
          {appAside}
        </aside>
      )}
    </section>
  );
};
ResponsiveLayout.displayName = "ResponsiveLayout";
