// packages/vuePage/src/components/app.nav.vue
<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { useResponsiveLayoutStore } from "responsive-layout-vue";

const store = useResponsiveLayoutStore();
</script>

<template>
  <nav class="grid place-items-center">
    <button
      class="absolute top-2 right-2 z-50 text-blue-500 text-2xl md:hidden"
      @click="store.toggleNav">
      <Icon icon="lucide:x" />
    </button>
    <h2 class="text-xl p-4">Navigation</h2>
  </nav>
</template>

// packages/rcPage/src/components/app.nav.tsx
import { useResponsiveLayoutStore, cn } from "responsive-layout-react";
import { Icon } from "@iconify/react";
export interface AppNavProps {
  className?: string;
}

export const AppNav = ({ className }: AppNavProps) => {
  const toggleNav = useResponsiveLayoutStore((state) => state.toggleNav);
  return (
    <div className={cn(" grid place-items-center", className)}>
      <button
        className="absolute top-2 right-2 z-50 text-blue-500 text-2xl md:hidden"
        onClick={toggleNav}>
        <Icon icon="lucide:x" />
      </button>
      <h1>APP NAV</h1>
    </div>
  );
};
AppNav.displayName = "AppNav";
