// packages/rcPage/src/App.tsx
import { ResponsiveLayout } from "responsive-layout-react";
import { AppHeader } from "./components/app.header";
import { AppNav } from "./components/app.nav";
import { AppAside } from "./components/app.aside";
import { AppMain } from "./components/app.main";
export interface AppProps {}

export const App = ({}: AppProps) => {
  return (
    <ResponsiveLayout
      className="text-gray-600 font-bold tracking-wider max-w-[2100px] mx-auto shadow-2xl"
      appNav={<AppNav className="w-full h-full bg-pink-50" />}
      navWidth="24rem"
      appAside={<AppAside className="w-full h-full bg-blue-50" />}
      asideWidth="18rem"
      appMain={
        <div className="w-full h-full  flex flex-col">
          <AppHeader className="bg-green-50" />
          <AppMain className="flex-1 bg-yellow-50" />
        </div>
      }
    />
  );
};
App.displayName = "App";

// packages/vuePage/src/App.vue
<script setup lang="ts">
import { ResponsiveLayout } from "responsive-layout-vue";
import AppHeader from "./components/app.header.vue";
import AppNav from "./components/app.nav.vue";
import AppAside from "./components/app.aside.vue";
import AppMain from "./components/app.main.vue";
</script>

<template>
  <ResponsiveLayout
    class="text-gray-600 font-bold tracking-wider max-w-[2100px] mx-auto shadow-2xl"
    :nav-width="'24rem'"
    :aside-width="'18rem'">
    <template #nav>
      <AppNav class="w-full h-full bg-pink-50" />
    </template>
    <template #aside>
      <AppAside class="w-full h-full bg-blue-50" />
    </template>
    <template #main>
      <div class="w-full h-full flex flex-col">
        <AppHeader class="bg-green-50" />
        <AppMain class="flex-1 bg-yellow-50" />
      </div>
    </template>
  </ResponsiveLayout>
</template>
