// packages/rcPage/src/components/app.aside.tsx
import { cn, useResponsiveLayoutStore } from "responsive-layout-react";
import { Icon } from "@iconify/react";
export interface AppAsideProps {
  className?: string;
}

export const AppAside = ({ className }: AppAsideProps) => {
  const toggleAside = useResponsiveLayoutStore((state) => state.toggleAside);
  return (
    <div className={cn("grid place-items-center", className)}>
      <button
        className="absolute top-2 left-2 z-50 md:hidden text-blue-500 text-2xl"
        onClick={toggleAside}>
        <Icon icon="lucide:x" />
      </button>
      <h1>APP ASIDE</h1>
    </div>
  );
};
AppAside.displayName = "AppAside";

// packages/vuePage/src/components/app.aside.vue
<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { useResponsiveLayoutStore } from "responsive-layout-vue";

const store = useResponsiveLayoutStore();
</script>

<template>
  <aside class="grid place-items-center relative">
    <button
      class="absolute top-2 left-2 z-50 md:hidden text-blue-500 text-2xl"
      @click="store.toggleAside">
      <Icon icon="lucide:x" />
    </button>
    <h2 class="text-xl p-4">Aside</h2>
  </aside>
</template>
